//
//  Random.swift
//  ArduinoKit
//
//  Created by Brent Van den Abbeel on 2025-11-04.
//

private let RANDOM_MAX: UInt32 = 0x7FFFFFFF
private var next: UInt32 = 1

/// Arduino Reference: Language/Functions/Random Numbers/randomSeed
///
/// `randomSeed()` initializes the pseudo-random number generator, causing it to start at an arbitrary point in its random sequence. This sequence, while very long, and random, is always the same.
/// If it is important for a sequence of values generated by `random()` to differ, on subsequent executions of a sketch, use `randomSeed()` to initialize the random number generator with a fairly random input, such as `analogRead()` on an unconnected pin.
// Conversely, it can occasionally be useful to use pseudo-random sequences the repeat exactly. This can be accomplished by calling `randomSeed()` with a fixed number, before starting the random sequence.
///
/// - Parameters:
/// - seed: non-zero number to initialize the pseudo-random sequence.
public func randomSeed(seed: UInt32) {
    if seed != 0 {
        next = seed
    }
}

/// Arduino Reference: Language/Functions/Random Numbers/random
///
/// The random function generates pseudo-random numbers.
///
/// - Returns: A random number between 0 (inclusive) and 4.294.967.295 (exclusive)
public func random() -> UInt32 {
    // Algorithm:
    // Compute x = (7^5 * x) mod (2^31 - 1)
    // without overflowing 31 bits:
    //     (2^31 - 1) = 1277773 * (7 ^5) + 2836
    // Inspired by avr-libc, who based their generator on:
    // "Random number generators: good ones are hard to find",
    // Park and Miller, Communications of the ACM, vol. 31, no. 10,
    // October 1988, p. 1195.
    var x = next
    
    if x == 0 { x = 123459876 }
    let high = x / 127773
    let low = x % 127773
    x = 16807 * low - 2836 * high
    
    next = x % (RANDOM_MAX + 1)
    return next
}

/// Arduino Reference: Language/Functions/Random Numbers/random
///
/// The random function generates pseudo-random numbers.
///
/// - Parameters:
/// - max: The upper bound of the random value, exclusive
/// - Returns: A random number between 0 (inclusive) and `max` (exclusive)
public func random(max: UInt32) -> UInt32 {
    guard max > 0 else { return 0 }
    return random() % max
}

/// Arduino Reference: Language/Functions/Random Numbers/random
///
/// The random function generates pseudo-random numbers.
///
/// - Parameters:
/// - min: The lower bound of the random value, inclusive
/// - max: The upper bound of the random value, exclusive
/// - Returns: A random number between `min` (inclusive) and `max` (exclusive)
public func random(min: UInt32, max: UInt32) -> UInt32 {
    guard min <= max else { return min }
    let difference = max - min
    
    return random(max: difference) + min
}
